var a = parseFloat(prompt('Digite o valor de a: '))
var b = parseFloat(prompt('Digite o valor de b: '))
var c = parseFloat(prompt('Digite o valor de c: '))
var soma = parseFloat((a**2)+(b**2)+(c**2))
alert('o resultado é: ' + soma)